const _ = require('lodash');
const { Path } = require('path-parser');
const { URL } = require('url');
const mongoose = require('mongoose');
const requireLogin = require('../middlewares/requireLogin');
const requireCredits = require('../middlewares/requireCredits');
const Mailer = require('../services/Mailer');
const surveyTemplate = require('../services/emailTemplates/surveyTemplate');

const Survey = mongoose.model('surveys');

module.exports = app => {
  app.get('/api/surveys/yes', (req, res) => {
    res.send(
      'We appreciate your feedback and we are happy to hear that you enjoyed our product!'
    );
  });

  app.post('/api/surveys/webhooks', (req, res) => {
    const p = new Path('/api/surveys/:surveyId/:choice');

    const events = _.chain(req.body)
      .map(({ email, url }) => {
        // const pathname = new URL(url).pathname;
        const match = p.test(new URL(url).pathname);
        // will return null if no surveyid and choice
        if (match) {
          return { email, surveyId: match.surveyId, choice: match.choice };
        }
      })

      .compact()
      .uniqBy('email', 'surveyId')
      .value();

    console.log(events);

    res.send({});
  });

  app.get('/api/surveys/no', (req, res) => {
    res.send(
      'We appreciate your feedback and we are sorry to hear that you did not enjoy our product'
    );
  });

  app.post('/api/surveys', requireLogin, requireCredits, async (req, res) => {
    const { title, subject, body, recipients } = req.body;

    const survey = new Survey({
      title,
      subject,
      body,
      recipients: recipients.split(',').map(email => ({ email: email.trim() })),
      _user: req.user.id,
      dateSent: Date.now()
      // this is the id property generated by mongoose
    });

    // GREAT PLACE TO SEND AN EMAIL!
    const mailer = new Mailer(survey, surveyTemplate(survey));
    try {
      await mailer.send();
      await survey.save();
      req.user.credits -= 1;
      const user = await req.user.save();

      res.send(user);
    } catch (err) {
      res.status(422).send(err);
    }
  });
};
